services:
  api:
    build: .
    container_name: barbearia_api
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=app.py
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/barbearia_db
      - JWT_SECRET_KEY=chave-super-secreta
    depends_on:
      db:
        condition: service_healthy
    command: >
      bash -c "flask db upgrade &&
               gunicorn --bind 0.0.0.0:5000 --workers 3 app:app"
  db:
    image: postgres:15-alpine
    container_name: barbearia_db
    restart: always
    environment:
      POSTGRES_DB: barbearia_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d barbearia_db"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
