"""Adiciona horarios e muda pra barbeiro_id

Revision ID: 0a313a2fb919
Revises: 8537ced82373
Create Date: 2026-04-03 22:07:17.708588

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a313a2fb919'
down_revision = '8537ced82373'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('empresas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hora_abertura', sa.Time(), nullable=True))
        batch_op.add_column(sa.Column('hora_fechamento', sa.Time(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('empresas', schema=None) as batch_op:
        batch_op.drop_column('hora_fechamento')
        batch_op.drop_column('hora_abertura')

    # ### end Alembic commands ###
