"""Renomeia profissional_id para barbeiro_id

Revision ID: 8537ced82373
Revises: 386416bbf29c
Create Date: 2026-04-03 21:44:30.625828

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8537ced82373'
down_revision = '386416bbf29c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agendamentos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('barbeiro_id', sa.UUID(), nullable=False))
        batch_op.drop_constraint(batch_op.f('agendamentos_profissional_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'usuarios', ['barbeiro_id'], ['id'])
        batch_op.drop_column('profissional_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agendamentos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profissional_id', sa.UUID(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('agendamentos_profissional_id_fkey'), 'usuarios', ['profissional_id'], ['id'])
        batch_op.drop_column('barbeiro_id')

    # ### end Alembic commands ###
