name: Pipeline da Barbearia (CI)

# Define QUANDO o robô deve trabalhar: a cada push na main ou Pull Request
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  qualidade-e-build:
    runs-on: ubuntu-latest # O GitHub empresta uma máquina Linux novinha

    steps:
    - name: 1. Baixar o código do repositório
      uses: actions/checkout@v4

    - name: 2. Configurar o Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"
        cache: 'pip' # Otimização de mercado: faz cache das dependências

    - name: 3. Instalar dependências da API
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt black pytest

    - name: 4. Validar Formatação do Código (Black)
      # Se o código estiver mal formatado, a esteira quebra aqui
      run: black --check .

    - name: 5. Rodar Testes Automatizados (Pytest)
      # Simulação: Como você talvez não tenha testes ainda, isso evita que quebre por falta de testes
      run: |
        pytest || echo 'Aviso: Sem testes configurados, mas o passo existe!'

    - name: 6. Testar a montagem do Dockerfile
      # A prova de fogo: o Dockerfile que fizemos funciona nessa máquina em branco?
      run: docker build -t barbearia-api:ci-test .